name: yuto tesuko
on: push

jobs:

  my_test:

    name: my test action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: yutodotcat
          password: ${{ secrets.GHCR }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/yutodotcat/github_action:latest

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: yutopoyo777
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: /yutodotcat/github_action:latest

